name: Auto Sync Fork

on:
  schedule:
    - cron: '0 5 * * 3,6'  # At 05:00 UTC on Wednesday and Saturday
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # Fetch all branches

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/Pasithea0/smov.git
          git fetch upstream --prune

      - name: Sync All Branches
        run: |
          for branch in $(git branch -r | grep upstream/ | sed 's/upstream\///'); do
            git checkout $branch || git checkout -b $branch
            git merge upstream/$branch --no-edit || echo "No new changes to merge"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $branch
          done
