name: Sync Fork

on:
  schedule:
    - cron: '0 5 * * 3,6'
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          token: ${{ github.token }}
          owner: Pasithea0
          repo: smov	
          base: production
          head: production
